language: python
python:
  - 2.7
  - 3.6
  
notifications:
  email: false

cache:
    apt: true
    pip: true


before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv

install:
  - pip install -r requirements.txt
  - conda install --channel rdkit


script:
  - nosetests --with-coverage --cover-inclusive --cover-package=. --cover-erase
  - coverage report --omit 'images/*,tests/*' --show-missing